module KeycloakClient
  self.@config: untyped

  self.@root: untyped

  attr_writer self.config: untyped

  def self.config: () -> untyped

  def self.configure: () { (untyped) -> untyped } -> untyped

  def self.root: () -> untyped
end

module KeycloakClient
  class AdminClient
    @realm: untyped

    @realm_stack: untyped

    @username: untyped

    @password: untyped

    @conn: untyped

    @token: untyped

    @token_expires_at: untyped

    include Resources::Users

    include Resources::Realms

    include Resources::Clients

    include Resources::Organizations

    include Resources::Roles

    include Resources::Groups

    include Resources::ClientScopes

    def initialize: (?realm: untyped?, ?username: untyped?, ?password: untyped?) -> void

    def authorize!: () -> untyped

    def for_realm: (untyped realm) { () -> untyped } -> untyped

    def authorize_if_needed: () -> (untyped | nil)

    def get: (untyped path, ?::Hash[untyped, untyped] params, ?::Hash[untyped, untyped] headers, ?admin_scoped: bool) -> untyped

    def put: (untyped path, ?::Hash[untyped, untyped] body, ?::Hash[untyped, untyped] headers, ?admin_scoped: bool) -> untyped

    def post: (untyped path, ?::Hash[untyped, untyped] body, ?::Hash[untyped, untyped] headers, ?admin_scoped: bool) -> untyped

    def delete: (untyped path, ?::Hash[untyped, untyped] params, ?::Hash[untyped, untyped] headers, ?admin_scoped: bool) -> untyped

    def form_post: (untyped path, ?::Hash[untyped, untyped] body, ?::Hash[untyped, untyped] headers, ?admin_scoped: bool) -> untyped

    def current_realm: () -> untyped

    private

    attr_reader token: untyped

    attr_reader token_expires_at: untyped

    attr_reader username: untyped

    attr_reader password: untyped
  end
end

module KeycloakClient
  class Configuration
    @host: untyped

    @client_id: untyped

    @client_secret: untyped

    @default_realm: untyped

    @default_client_id: untyped

    @default_client_secret: untyped

    attr_accessor host: untyped

    attr_accessor client_id: untyped

    attr_accessor client_secret: untyped

    attr_accessor default_realm: untyped

    attr_accessor default_client_id: untyped

    attr_accessor default_client_secret: untyped

    def initialize: () -> void
  end
end

module KeycloakClient
  class Railtie < Rails::Railtie
  end
end

module KeycloakClient
  module Resources
  end
end

module KeycloakClient
  module Resources
    module ClientScopes
      def client_scopes: (?::Hash[untyped, untyped] params) -> untyped

      def create_client_scope: (untyped scope) -> untyped

      def add_default_client_scope: (untyped client_id, untyped scope_id) -> untyped

      def remove_default_client_scope: (untyped client_id, untyped scope_id) -> untyped

      def add_optional_client_scope: (untyped client_id, untyped scope_id) -> untyped

      def remove_optional_client_scope: (untyped client_id, untyped scope_id) -> untyped
    end
  end
end

module KeycloakClient
  module Resources
    module Clients
      def clients: () -> untyped

      def client: (untyped client_uuid) -> untyped

      def create_client: (untyped client) -> untyped

      def delete_client: (untyped client_uuid) -> untyped

      def update_client: (untyped client_uuid, untyped client) -> untyped

      def get_client_secret: (untyped client_uuid) -> untyped

      def generate_client_secret: (untyped client_uuid) -> untyped

      def get_installation_provider: (untyped client_uuid, untyped provider_id) -> untyped

      def get_service_account_user: (untyped client_uuid) -> untyped

      def push_client_revocation_policy: (untyped client_uuid) -> untyped

      def test_client_clusters_availability: (untyped client_uuid) -> untyped

      def get_client_sessions: (untyped client_uuid) -> untyped

      def get_client_offline_sessions: (untyped client_uuid) -> untyped

      def register_client_cluster_node: (untyped client_uuid) -> untyped

      def unregister_client_cluster_node: (untyped client_uuid, untyped node) -> untyped

      def get_client_session_stats: (untyped client_uuid) -> untyped
    end
  end
end

module KeycloakClient
  module Resources
    module Groups
      def groups: (?::Hash[untyped, untyped] params) -> untyped

      def subgroups: (untyped group_id) -> untyped

      def group_by_path: (untyped path) -> (nil | untyped)

      def group: (untyped id) -> untyped

      def create_group: (untyped group, ?parent_id: untyped?) -> untyped

      def update_group: (untyped id, untyped group) -> untyped

      def delete_group: (untyped id) -> untyped

      def group_members: (untyped id) -> untyped

      def add_group_member: (untyped group_id, untyped user_id) -> untyped

      def remove_group_member: (untyped group_id, untyped user_id) -> untyped
    end
  end
end

module KeycloakClient
  module Resources
    module Organizations
      def organizations: (?::Hash[untyped, untyped] params) -> untyped

      def organization_by_alias: (untyped org_alias) -> untyped

      def organization: (untyped organization_id) -> untyped

      def delete_organization: (untyped organization_id) -> untyped

      def update_organization: (untyped organization_id, untyped organization) -> untyped

      def create_organization: (untyped organization) -> untyped

      def get_organization_member_count: (untyped organization_id) -> untyped

      # TODO: Add pagination
      def get_organization_members: (untyped organization_id) -> untyped

      def invite_existing_user: (untyped organization_id, untyped user_id) -> untyped

      # Note: This uses a form post instead of a typcial JSON body
      def invite_user: (untyped organization_id, untyped email) -> untyped

      def create_organization_membership: (untyped organization_id, untyped user_id) -> untyped

      def remove_user: (untyped organization_id, untyped user_id) -> untyped

      def get_organization_member: (untyped organization_id, untyped member_id) -> untyped

      def get_organization_memberships: (untyped organization_id, untyped user_id) -> untyped
    end
  end
end

module KeycloakClient
  module Resources
    module Realms
      def realms: () -> untyped

      def realm: (untyped realm_name) -> untyped

      def create_realm: (untyped realm) -> untyped

      def delete_realm: (untyped realm_name) -> untyped

      def update_realm: (untyped realm_name, untyped realm) -> untyped

      def get_client_session_stats: (untyped realm_name) -> untyped
    end
  end
end

module KeycloakClient
  module Resources
    module Roles
      # Get realm-level roles
      def realm_roles: () -> untyped

      # Get a specific realm-level role by name
      def get: (untyped name) -> untyped

      def client_roles: (untyped client_id) -> untyped

      def user_roles: (untyped user_id) -> untyped

      def assign_client_role: (untyped role, client_id: untyped, user_id: untyped) -> untyped

      # Create a new realm-level role
      def create: (untyped role_representation) -> untyped

      # Update a realm-level role by name
      def update: (untyped name, untyped role_representation) -> untyped

      # Delete a realm-level role by name
      def delete: (untyped name) -> untyped

      # Get composite roles for a realm-level role
      def get_composites: (untyped name) -> untyped

      # Add composite roles to a realm-level role
      def add_composites: (untyped name, untyped roles) -> untyped

      # Remove composite roles from a realm-level role
      def delete_composites: (untyped name, untyped roles) -> untyped

      # Get realm-level roles in a role's composite
      def get_realm_composites: (untyped name) -> untyped

      # Get client-level roles for a client in a role's composite
      def get_client_composites: (untyped name, untyped client_id) -> untyped
    end
  end
end

module KeycloakClient
  module Resources
    module Users
      def user_count: () -> untyped

      def users: (?::Hash[untyped, untyped] params) -> untyped

      def user: (untyped user_id) -> untyped

      def create_user: (untyped user) -> untyped

      def delete_user: (untyped user_id) -> untyped

      def update_user: (untyped user_id, untyped user) -> untyped

      def send_reset_password_email: (untyped user_id) -> untyped

      def send_verify_email: (untyped user_id) -> untyped

      def get_user_sessions: (untyped user_id) -> untyped
    end
  end
end

module KeycloakClient
  VERSION: "0.1.0"
end

module Middleware
  module Faraday
    class SymbolizeJson < ::Faraday::Middleware
      def on_complete: (untyped env) -> (nil | untyped)
    end
  end
end
